# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import fraud_detection_pb2 as fraud__detection__pb2

GRPC_GENERATED_VERSION = '1.73.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in fraud_detection_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FraudDetectionServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.InitializeFraudOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/InitializeFraudOrder',
                request_serializer=fraud__detection__pb2.FraudRequest.SerializeToString,
                response_deserializer=fraud__detection__pb2.FraudResponse.FromString,
                _registered_method=True)
        self.CheckUserFraud = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/CheckUserFraud',
                request_serializer=fraud__detection__pb2.Empty.SerializeToString,
                response_deserializer=fraud__detection__pb2.FraudResponse.FromString,
                _registered_method=True)
        self.CheckCardFraud = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/CheckCardFraud',
                request_serializer=fraud__detection__pb2.Empty.SerializeToString,
                response_deserializer=fraud__detection__pb2.FraudResponse.FromString,
                _registered_method=True)
        self.ClearFraudOrder = channel.unary_unary(
                '/fraud_detection.FraudDetectionService/ClearFraudOrder',
                request_serializer=fraud__detection__pb2.Empty.SerializeToString,
                response_deserializer=fraud__detection__pb2.FraudResponse.FromString,
                _registered_method=True)


class FraudDetectionServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def InitializeFraudOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckUserFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckCardFraud(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ClearFraudOrder(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FraudDetectionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'InitializeFraudOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.InitializeFraudOrder,
                    request_deserializer=fraud__detection__pb2.FraudRequest.FromString,
                    response_serializer=fraud__detection__pb2.FraudResponse.SerializeToString,
            ),
            'CheckUserFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckUserFraud,
                    request_deserializer=fraud__detection__pb2.Empty.FromString,
                    response_serializer=fraud__detection__pb2.FraudResponse.SerializeToString,
            ),
            'CheckCardFraud': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckCardFraud,
                    request_deserializer=fraud__detection__pb2.Empty.FromString,
                    response_serializer=fraud__detection__pb2.FraudResponse.SerializeToString,
            ),
            'ClearFraudOrder': grpc.unary_unary_rpc_method_handler(
                    servicer.ClearFraudOrder,
                    request_deserializer=fraud__detection__pb2.Empty.FromString,
                    response_serializer=fraud__detection__pb2.FraudResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'fraud_detection.FraudDetectionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('fraud_detection.FraudDetectionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FraudDetectionService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def InitializeFraudOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_detection.FraudDetectionService/InitializeFraudOrder',
            fraud__detection__pb2.FraudRequest.SerializeToString,
            fraud__detection__pb2.FraudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckUserFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_detection.FraudDetectionService/CheckUserFraud',
            fraud__detection__pb2.Empty.SerializeToString,
            fraud__detection__pb2.FraudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CheckCardFraud(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_detection.FraudDetectionService/CheckCardFraud',
            fraud__detection__pb2.Empty.SerializeToString,
            fraud__detection__pb2.FraudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ClearFraudOrder(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/fraud_detection.FraudDetectionService/ClearFraudOrder',
            fraud__detection__pb2.Empty.SerializeToString,
            fraud__detection__pb2.FraudResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
