# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: fraud_detection.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'fraud_detection.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x66raud_detection.proto\x12\x0f\x66raud_detection\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"\x90\x01\n\x0c\x46raudRequest\x12\x13\n\x0b\x63\x61rd_number\x18\x01 \x01(\t\x12\x14\n\x0corder_amount\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\r\n\x05\x65mail\x18\x04 \x01(\t\x12\x38\n\x0f\x62illing_address\x18\x05 \x01(\x0b\x32\x1f.fraud_detection.BillingAddress\"2\n\rFraudResponse\x12\x10\n\x08is_fraud\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xcd\x02\n\x15\x46raudDetectionService\x12U\n\x14InitializeFraudOrder\x12\x1d.fraud_detection.FraudRequest\x1a\x1e.fraud_detection.FraudResponse\x12H\n\x0e\x43heckUserFraud\x12\x16.fraud_detection.Empty\x1a\x1e.fraud_detection.FraudResponse\x12H\n\x0e\x43heckCardFraud\x12\x16.fraud_detection.Empty\x1a\x1e.fraud_detection.FraudResponse\x12I\n\x0f\x43learFraudOrder\x12\x16.fraud_detection.Empty\x1a\x1e.fraud_detection.FraudResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'fraud_detection_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BILLINGADDRESS']._serialized_start=42
  _globals['_BILLINGADDRESS']._serialized_end=133
  _globals['_FRAUDREQUEST']._serialized_start=136
  _globals['_FRAUDREQUEST']._serialized_end=280
  _globals['_FRAUDRESPONSE']._serialized_start=282
  _globals['_FRAUDRESPONSE']._serialized_end=332
  _globals['_EMPTY']._serialized_start=334
  _globals['_EMPTY']._serialized_end=341
  _globals['_FRAUDDETECTIONSERVICE']._serialized_start=344
  _globals['_FRAUDDETECTIONSERVICE']._serialized_end=677
# @@protoc_insertion_point(module_scope)
