# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: books_database.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'books_database.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x62ooks_database.proto\x12\x0e\x62ooks_database\"\x1c\n\x0bReadRequest\x12\r\n\x05title\x18\x01 \x01(\t\"\x1d\n\x0cReadResponse\x12\r\n\x05stock\x18\x01 \x01(\x05\"0\n\x0cWriteRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x11\n\tnew_stock\x18\x02 \x01(\x05\" \n\rWriteResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"6\n\x13TryDecrementRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\'\n\x14TryDecrementResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\"3\n\x10IncrementRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"$\n\x11IncrementResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xc5\x02\n\rBooksDatabase\x12\x41\n\x04Read\x12\x1b.books_database.ReadRequest\x1a\x1c.books_database.ReadResponse\x12\x44\n\x05Write\x12\x1c.books_database.WriteRequest\x1a\x1d.books_database.WriteResponse\x12Y\n\x0cTryDecrement\x12#.books_database.TryDecrementRequest\x1a$.books_database.TryDecrementResponse\x12P\n\tIncrement\x12 .books_database.IncrementRequest\x1a!.books_database.IncrementResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'books_database_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_READREQUEST']._serialized_start=40
  _globals['_READREQUEST']._serialized_end=68
  _globals['_READRESPONSE']._serialized_start=70
  _globals['_READRESPONSE']._serialized_end=99
  _globals['_WRITEREQUEST']._serialized_start=101
  _globals['_WRITEREQUEST']._serialized_end=149
  _globals['_WRITERESPONSE']._serialized_start=151
  _globals['_WRITERESPONSE']._serialized_end=183
  _globals['_TRYDECREMENTREQUEST']._serialized_start=185
  _globals['_TRYDECREMENTREQUEST']._serialized_end=239
  _globals['_TRYDECREMENTRESPONSE']._serialized_start=241
  _globals['_TRYDECREMENTRESPONSE']._serialized_end=280
  _globals['_INCREMENTREQUEST']._serialized_start=282
  _globals['_INCREMENTREQUEST']._serialized_end=333
  _globals['_INCREMENTRESPONSE']._serialized_start=335
  _globals['_INCREMENTRESPONSE']._serialized_end=371
  _globals['_BOOKSDATABASE']._serialized_start=374
  _globals['_BOOKSDATABASE']._serialized_end=699
# @@protoc_insertion_point(module_scope)
