# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: transaction_verification.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'transaction_verification.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1etransaction_verification.proto\x12\x18transaction_verification\"[\n\x0e\x42illingAddress\x12\x0e\n\x06street\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x0b\n\x03zip\x18\x04 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x05 \x01(\t\"*\n\x08\x42ookItem\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08quantity\x18\x02 \x01(\x05\"\xe3\x01\n\x13VerificationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x13\n\x0b\x63\x61rd_number\x18\x03 \x01(\t\x12\x17\n\x0f\x65xpiration_date\x18\x04 \x01(\t\x12\x0b\n\x03\x63vv\x18\x05 \x01(\t\x12\x41\n\x0f\x62illing_address\x18\x06 \x01(\x0b\x32(.transaction_verification.BillingAddress\x12\x31\n\x05items\x18\x07 \x03(\x0b\x32\".transaction_verification.BookItem\"9\n\x14VerificationResponse\x12\x10\n\x08is_valid\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty2\xa9\x05\n\x1eTransactionVerificationService\x12|\n\x1bInitializeVerificationOrder\x12-.transaction_verification.VerificationRequest\x1a..transaction_verification.VerificationResponse\x12h\n\x15StartVerificationFlow\x12\x1f.transaction_verification.Empty\x1a..transaction_verification.VerificationResponse\x12\x65\n\x12\x43heckItemsNotEmpty\x12\x1f.transaction_verification.Empty\x1a..transaction_verification.VerificationResponse\x12i\n\x16\x43heckMandatoryUserData\x12\x1f.transaction_verification.Empty\x1a..transaction_verification.VerificationResponse\x12\x62\n\x0f\x43heckCardFormat\x12\x1f.transaction_verification.Empty\x1a..transaction_verification.VerificationResponse\x12i\n\x16\x43learVerificationOrder\x12\x1f.transaction_verification.Empty\x1a..transaction_verification.VerificationResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transaction_verification_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_BILLINGADDRESS']._serialized_start=60
  _globals['_BILLINGADDRESS']._serialized_end=151
  _globals['_BOOKITEM']._serialized_start=153
  _globals['_BOOKITEM']._serialized_end=195
  _globals['_VERIFICATIONREQUEST']._serialized_start=198
  _globals['_VERIFICATIONREQUEST']._serialized_end=425
  _globals['_VERIFICATIONRESPONSE']._serialized_start=427
  _globals['_VERIFICATIONRESPONSE']._serialized_end=484
  _globals['_EMPTY']._serialized_start=486
  _globals['_EMPTY']._serialized_end=493
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_start=496
  _globals['_TRANSACTIONVERIFICATIONSERVICE']._serialized_end=1177
# @@protoc_insertion_point(module_scope)
