# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: executor.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'executor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x65xecutor.proto\x12\x08\x65xecutor\"&\n\x0f\x45lectionRequest\x12\x13\n\x0b\x63\x61ndidateId\x18\x01 \x01(\x05\"!\n\x10\x45lectionResponse\x12\r\n\x05\x61live\x18\x01 \x01(\x08\"\"\n\x0eVictoryRequest\x12\x10\n\x08leaderId\x18\x01 \x01(\x05\"\'\n\x0fVictoryResponse\x12\x14\n\x0c\x61\x63knowledged\x18\x01 \x01(\x08\x32\x94\x01\n\x0f\x45xecutorService\x12\x41\n\x08\x45lection\x12\x19.executor.ElectionRequest\x1a\x1a.executor.ElectionResponse\x12>\n\x07Victory\x12\x18.executor.VictoryRequest\x1a\x19.executor.VictoryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'executor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ELECTIONREQUEST']._serialized_start=28
  _globals['_ELECTIONREQUEST']._serialized_end=66
  _globals['_ELECTIONRESPONSE']._serialized_start=68
  _globals['_ELECTIONRESPONSE']._serialized_end=101
  _globals['_VICTORYREQUEST']._serialized_start=103
  _globals['_VICTORYREQUEST']._serialized_end=137
  _globals['_VICTORYRESPONSE']._serialized_start=139
  _globals['_VICTORYRESPONSE']._serialized_end=178
  _globals['_EXECUTORSERVICE']._serialized_start=181
  _globals['_EXECUTORSERVICE']._serialized_end=329
# @@protoc_insertion_point(module_scope)
